### ISSUE TITLE
Ağaç Türü Eklenmesi Talebi

### ISSUE THREAD

**Issue by teknikofis14** [firatoglakci/agaclandirma#10]
Taşra İşlemleri Ekranına Tanımlamalar menüsünün altına Ağaç Türü Eklenmesi Talebi alt menüsü eklenerek Merkez Koordinasyon tarafından veritabanına eklenmesi istenilen ağaç türleri gönderilebilecek.

**Comment by cep78** [comment]
ekleme silme düğmeleri gözükmüyor visual studio da

**Comment by teknikofis14** [comment]
> ekleme silme düğmeleri gözükmüyor visual studio da

Düzeltildi.

**Comment by teknikofis14** [comment]
Tasarım eklendi. Kodlama yapılacak.

**Comment by cep78** [comment]
kodlama yapıldı deneme yapılması gerekiyor
