### ISSUE TITLE
Kullanıcı Tanımlama Formu

### ISSUE THREAD

**Issue by teknikofis14** [firatoglakci/agaclandirma#12]
Kullanıcı Tanımlama Formu'ndaki Şifre Değiştirme kodlama yapılacak. Ayrıca Merkez Koordinasyonda görevli personel Kullanıcı Tanımlama yaparken tüm yetki türlerini görüntüleyebiliyor. Bunun üzerine bir düşünelim. Her yetkiyi veremesin diye düşünüyorum.

**Comment by cep78** [comment]
sorun düzeltildi
