### ISSUE TITLE
Ağaçlandırma Alanı Fotoğrafı Ekleme Hatası

### ISSUE THREAD

**Issue by teknikofis14** [firatoglakci/agaclandirma#3]
Ağaçlandırma Alanı Fotoğrafı Ekleme Formu'nda Faaliyet Seçimi Veri Tablosu'nda bir satır seçildikten sonra tekrar satıra çift tıklandığında "**Uygulamanızda İşlenmemiş özel bir durum oluştu**" uyarısı vermektedir.
**Fotoğraf adlı sütun bulunamıyor.
Parametre adı: columnName.**

**Comment by firatoglakci** [comment]
Sorun giderildi.
