### ISSUE TITLE
Bakım Faaliyeti Ekranı

### ISSUE THREAD

**Issue by teknikofis14** [firatoglakci/agaclandirma#4]
Bakım Faaliyeti ekranında bakımı yapılan ağaç sayısı toplam ağaç sayısından fazla girilebilmektedir. Bakım Alanı Bilgilerini Kaydet ve Sonraki Adıma Geç düğmesine ağaç sayısı kontrolü eklenmeli.

**Comment by cep78** [comment]
Gerekli Kontrol Tamamlandı
