### ISSUE TITLE
Taşra İşlemleri Formu'nda Ağaçlandırma Sahası seçildiğinde harita güncellenmiyor

### ISSUE THREAD

**Issue by teknikofis14** [firatoglakci/agaclandirma#6]
Taşra İşlemleri Formu'nda Ağaçlandırma Sahası seçildiğinde haritada sadece ilgili ağaçlandırma sahası görünmüyor.

**Comment by cep78** [comment]
hata giderildi

**Comment by cep78** [comment]
hata giderildi
